# Generated by Django 2.1.7 on 2019-10-01 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20190907_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='sharedMessage',
            fields=[
                ('message_id', models.IntegerField(primary_key=True, serialize=False)),
                ('file_location', models.FilePathField(max_length=300)),
                ('link', models.TextField()),
                ('local_time', models.DateTimeField()),
                ('ust_time', models.DateTimeField()),
                ('exp_time', models.IntegerField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
